config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'
  resources :films, only: [:index, :show]
  get '/errors/:id', '/errors', to: 'errors#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  banner     :string           default("🏳️"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Country < ApplicationRecord
end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id          :bigint           not null, primary key
#  season_id   :bigint           not null
#  title       :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Episode < ApplicationRecord
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id              :bigint           not null, primary key
#  title           :string           not null
#  description     :text
#  release_date    :date             default(Thu, 01 Jan 1970), not null
#  duration        :integer          not null
#  age_restriction :integer          default(0), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Film < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :release_date, timeliness: { on_or_after: '01.01.1895', on_or_before: Time.zone.today, type: :date }
  validates :duration,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 3 }
  validates :age_restriction,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 21 }

  has_one_attached :main_image
  has_many_attached :images
end

app/models/film_category.rb
# == Schema Information
#
# Table name: film_categories
#
#  id          :bigint           not null, primary key
#  film_id     :bigint           not null
#  category_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class FilmCategory < ApplicationRecord
end

app/models/film_country.rb
# == Schema Information
#
# Table name: film_countries
#
#  id         :bigint           not null, primary key
#  country_id :bigint           not null
#  film_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class FilmCountry < ApplicationRecord
end

app/models/film_person.rb
# == Schema Information
#
# Table name: film_people
#
#  id         :bigint           not null, primary key
#  film_id    :bigint           not null
#  person_id  :bigint           not null
#  role       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class FilmPerson < ApplicationRecord
end

app/models/film_tag.rb
# == Schema Information
#
# Table name: film_tags
#
#  id         :bigint           not null, primary key
#  film_id    :bigint           not null
#  tag_id     :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class FilmTag < ApplicationRecord
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :bigint           not null, primary key
#  first_name :string           not null
#  surname    :string           not null
#  patronymic :string
#  birthday   :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Person < ApplicationRecord
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :bigint           not null, primary key
#  text       :text             not null
#  rating     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Review < ApplicationRecord
end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id           :bigint           not null, primary key
#  film_id      :bigint           not null
#  number       :integer
#  title        :string           not null
#  description  :text
#  release_date :date             not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Season < ApplicationRecord
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  name                   :string           not null
#  nickname               :string
#  role                   :integer          default("subscriber")
#  birthday               :date             not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { admin: 0, editor: 1, subscriber: 2 }

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :error

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: %i[email encrypted_password name nickname birthday]
    )
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: %i[password password_confirmation name
               nickname birthday current_password]
    )
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all.page params[:page]
  end

  def show
    @film = Film.find_by(id: params[:id])
    redirect_to root_path, error: 'Page with this film not found' unless @film
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @widget_size = 5
    # Search for films by genre will be carried out as
    # Film.where(genre: 'genre name').sample(@widget_size)
    # or Film.includes(:genres).where(genres: { name: 'genre name' }).order(rating: :desc).limit(@widget_size)
    # when genres will be added
    @action_movies = Film.all.sample(@widget_size)
    @westerns = Film.all.sample(@widget_size)
    @gangsters = Film.all.sample(@widget_size)
    @detectives = Film.all.sample(@widget_size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/films/index.html.erb
<div class="container-fluid main-theme-background">
  <div class="row"><h1 class="text-center">List of films</h1></div>
  <table class="table" height="100%">
    <tbody>
      <% @films.each do |film| %>
        <tr>
          <td width="15%">
            <div class="row">
              <%= link_to(film) do %>
                <% if film.main_image.representable? %>
                  <%= image_tag(film.main_image.representation(resize_to_limit: [100, 100]), class: 'img-fluid height-20') %>
                <% else %>
                  <%= image_tag('default_image3.png', class: 'img-fluid height-20') %>
                <% end %>
                <div class='col' height="20%"><%= film.title %></div>
              <% end %>
            </div>
          </td>
          <td width="10%"><%= film.release_date.year %></td>
          <td width="75%"><%= film.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @films, outer_window: 3 %>
</div>

app/views/films/show.html.erb
<div class="container-fluid main-theme-background">
  <div class="row">
    <div class="col-2">
      <div class="row">
        <% if @film.main_image.representable? %>
          <%= image_tag(@film.main_image.representation(resize_to_limit: [100, 100]), class: 'img-fluid height-20') %>
        <% else %>
          <%= image_tag('default_image3.png', class: 'img-fluid height-20') %>
        <% end %>
        <p class="text-center"><%= @film.release_date.year %></p>
      </div>
    </div>
    <div class="col-10">
      <div class="row"><h1 class="text-center"><%= @film.title %></h1></div>
      <div class="row"><h4><%= @film.description %></h4></div>
      <div class="row"><p>Duration: <%= @film.duration %></p></div>
      <div class="row"><p>Age restriction: <%= @film.age_restriction %></p></div>
      <div class="row">
        <p>Screenshotes:</p>
        <div class="container">
          <div class="row">
            <% @film.images.each do |image| %>
              <% if image.representable? %>
                <div class="col">
                  <%= image_tag(image.representation(resize_to_limit: [100, 100]), class: 'img-fluid height-20') %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_category_widget.html.erb
<div class="row home-page_background_<%= background %>">
<div class="row">
  <h2 class="home-page_headers-style"><%= category_name %></h2>
</div>
<div class="row">
  <% films_list.each do |film| %>
      <div class="col">
        <%= link_to(film, {class: 'home-page_headers-style'}) do %>
          <% if film.main_image.representable? %>
            <%= image_tag(film.main_image.representation(resize_to_limit: [100, 100]), class: 'img-fluid height-20') %>
          <% else %>
            <%= image_tag('default_image3.png', class: 'img-fluid height-20') %>
          <% end %>
          <div class="col home-page_headers-style"><%= film.title %></div>
        <% end %>
      </div>
  <% end %>
</div>
</div>

app/views/home/index.html.erb
<div class="container-fluid main-theme-background">
  <div class="row">
    <h1 class="text-center">Welcome to cinematichub</h1>
  </div>
  <div class="row">
    <%= link_to(films_path, style: 'text-decoration: none') do %>
      <h1 class="text-center"> Show all films</h1>
    <% end %>
  </div>
  <%= render 'category_widget',
      category_name: 'Action movies',
      films_list: @action_movies,
      background: 'action-movies' %>
  <%= render 'category_widget',
      category_name: 'Westerns',
      films_list: @westerns,
      background: 'westerns' %>
  <%= render 'category_widget',
      category_name: 'Gangsters',
      films_list: @gangsters,
      background: 'gangsters' %>
  <%= render 'category_widget',
      category_name: 'Detectives',
      films_list: @detectives,
      background: 'detectives' %>
</div>

app/views/layouts/_footer.html.erb
<hr />
<div class="container-fluid" style="height: 15vh; justify-content">
  <div class="row">
    <div class="col">
      <a class="navbar-brand" style="color: black; text-decoration: none" href="<%= root_path %>" >
        <%= image_tag('emblem.png', class: 'emblem-size_mini') %>
        cinematichub
      </a>
    </div>
    <div class="col">2022</div>
    <div class="col">
      Designed for: 
      <%= link_to ":iTechArt", "https://stlab.itechart-group.com" %>
    </div>
    <div class="col">
      Developer: 
      <%= link_to nil, "https://github.com/alhimick-prog" %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg main-theme-background">
  <div class="container-fluid">
    <div class="col-2">
      <a class="navbar-brand emblem-text" href="<%= root_path %>" >
        <%= image_tag('emblem.png', class: 'emblem-size') %>
        cinematichub
      </a>
    </div>
    <div class="col-7">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="row row-cols-auto">
        <div class="col">
          <ul class="navbar-nav mr-auto">
            <div class="col">
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Menu
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a class="dropdown-item" href="<%= root_path %>">Main page</a>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <a class="dropdown-item" href="<%= films_path %>">List of films</a>
                  </li>
                  <li><a class="dropdown-item" href="#">Another list (people)</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something (user profile)</a></li>
                </ul>
              </div>
            </div>
            <div class="col">
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Another menu (optional)
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Link to something</a></li>
                  <li><a class="dropdown-item" href="#">Something else</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Another link</a></li>
                </ul>
              </div>
            </div>
          </ul>
        </div>
        <div class="col">
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search film" aria-label="Search">
            <button class="btn btn-primary" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="row row-cols-auto">
        <div class="col"><a class="btn btn-primary" href="<%= new_user_session_path %>" role="submit">Sign in</a></div>
        <div class="col"><a class="btn btn-primary" href="<%= new_user_registration_path %>" role="button">Sign up</a></div>
        <div class="col"><a class="btn btn-primary" href="<%= edit_user_registration_path %>" role="button">Edit profile</a></div>
        <div class="col"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinematichub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main-theme-background">
    <%= render 'layouts/header' %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t('errors.messages.not_saved',
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to 'Log in', new_session_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to 'Sign up', new_registration_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to 'Forgot your password?', new_password_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br>
  <% end %>
<% end %>